package levelfileformats;

import java.io.FileOutputStream;
import levelmodel.DummyObject;
import levelmodel.DummyObjectList;
import levelmodel.LevelFileInterface;
import leveledit.ResFileReader;
import levelmodel.TileMap;

/**
 *
 *  LevelEdit internal file format.
 */
public class InternalLevelFile 
implements LevelFileInterface {
    
    private String path;
    
    /**
     * Is created for specific file.
     */
    public InternalLevelFile(String path) {
        this.path = path;
    }
    
    /**
     * Write level to file.
     * 
     * @return true if ok.
     */
    @Override
    public boolean write(DummyObjectList dummyObjects, TileMap tileMap) {
        try {
	
	    FileOutputStream f = new FileOutputStream(path);

	    // filename
	    f.write(new String("# "+"Level generated by LevelEdit.").getBytes());
	    f.write(new String("\r\n# "+path+"\r\n").getBytes());
	    f.write(new String("# "+"\r\n\r\n").getBytes());

	    // map array
            for (int n = 0; n < tileMap.getNumLayers(); n++) {
                
                // for backwards compat.:
                String layerNum = "" + (n + 1);
                if (n == 0) layerNum = "";
                
                f.write(new String("[map"+layerNum+"]" + "\r\n").getBytes());
                f.write(new String(Integer.toString(tileMap.getWidth())).getBytes());
                f.write(new String(" " + Integer.toString(tileMap.getHeight()) + "\r\n").getBytes());
                String data = new String();
                int w = tileMap.getWidth();
                int h = tileMap.getHeight();
                for (int j = 0; j < h; j++) {
                    for (int i = 0; i < w; i++) {

                        data += Integer.toString(tileMap.getTileVal(i, j, n)) + " ";
                    }
                }
                f.write(new String(data + "\r\n\r\n").getBytes());
            }
	    
	    // objects
	    f.write(new String("[init]"+"\r\n").getBytes());
	    DummyObject p;
	    for (int i = 0; i < dummyObjects.size(); i++)
	    {
		p = (DummyObject)dummyObjects.elementAt(i);
				
		String objdata = new String(
					  "new " + p.name + '\t' +
					  p.x + '\t' + p.y + '\t' + p.w + '\t' + p.h + '\t' +
					  p.additionalData + "\r\n"
					  );
		
		f.write(objdata.getBytes());		
	    }	   	    
	    f.write(new String("end"+"\r\n").getBytes());

	    f.close();	    
	} catch (Exception e) {}
        return true;
    }
    
    /**
     * Read a level into memory.
     * @return true if ok.
     */
    @Override
    public boolean read(DummyObjectList dummyObjects, DummyObject [] dummyTypes, 
        TileMap tileMap) {

	System.out.println("Opening .level file");
	try 
	{ 
	    ResFileReader r;
	    r = new ResFileReader(path);
	    
	    // load tilemap, post names are map, map2, map3 etc.
	    r.gotoPost("map", false);
	    tileMap.setMap(r.readMapArray(), 0);

            boolean layersLeft = true;
            int mapIndex = 2;
            while(layersLeft) {
                try {
                    r.gotoPost("map"+mapIndex, false);
                    tileMap.addMap(r.readMapArray());
                    mapIndex ++;
                } catch (Exception e) {
                    layersLeft = false;
                }
            }

	    // load objects
	    r.gotoPost("init",false);
	    r.nextLine();
	    int loops = 0;
	    while (r.getWord().compareTo("end") != 0 && loops < 1000)
	    {
		loops ++;
		if (r.getWord().compareTo("new") == 0)
		{
		    System.out.println("Adding dummy...");
		    String type = r.getNextWord();
		    int x = r.getNextWordAsInt();
		    int y = r.getNextWordAsInt();
		    int w = r.getNextWordAsInt();
		    int h = r.getNextWordAsInt();
		    String addData = r.getRestOfLine();
		    
		    DummyObject dummy ;
		    boolean found = false;
		    for (int i = 0; i < dummyTypes.length; i++){
			if (dummyTypes[i].name.compareTo(type)==0){
			    found = true;
			    dummy = new DummyObject(dummyTypes[i]);
			    dummy.x = x;
			    dummy.y = y;
			    dummy.w = w;
			    dummy.h = h;
			    dummy.additionalData = addData;
			    dummyObjects.newDummy(dummy);
			}
		    }
		    if (!found){
			System.out.println(
			    "Warning: dummytype "
			    +type+" not defined in def.file!");
		    }
		}
		r.nextLine();
	    }

	}
	catch (Exception e) {
            e.printStackTrace();
	    System.out.println("Error reading *.level file!");
	    return false;
	}

	System.out.println("Init finished");
        return true;
    }   
}